language: java

sudo: true

jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.m2

env:
  - KUBECTL_VERSION=v1.20.1
  - KUBECTL_VERSION=v1.19.1
  - KUBECTL_VERSION=v1.18.8
  - KUBECTL_VERSION=v1.17.9
  - KUBECTL_VERSION=v1.16.14

install:
- curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl
- chmod +x ./kubectl
- sudo mv ./kubectl /usr/local/bin/kubectl

script:
- mvn clean test findbugs:check

after_success:
- mvn jacoco:report coveralls:report
