language: java

sudo: true

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
  - $HOME/.m2

env:
  - KUBECTL_VERSION=v1.21.0
  - KUBECTL_VERSION=v1.20.6
  - KUBECTL_VERSION=v1.19.10
  - KUBECTL_VERSION=v1.18.18
  - KUBECTL_VERSION=v1.17.17
  - KUBECTL_VERSION=v1.16.15

install:
- curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl
- chmod +x ./kubectl
- sudo mv ./kubectl /usr/local/bin/kubectl

script:
- mvn clean test findbugs:check

after_success:
- mvn jacoco:report coveralls:report
